### ISSUE TITLE
إضافة مشروع

### ISSUE THREAD

**Issue by MoAlyousef** [SaudiOpenSourceCommunity/SaudiOSS#16]
السلام عليكم 
حاب أضيف مشروعي للفائدة
اسمه vcbld
وهو عبارة عن تطبيق لبناء برامج c++ 
باستخدام vcpkg.

**Comment by Alaboudi1** [comment]
وعليكم السلام نتشرف بإضافة مشروعك 
تقدر تضيفه عن طريق fork
أو تضع رابط المشروع هنا وبإذن الله بضيفة

**Comment by MoAlyousef** [comment]
أنا متشرف بكم
جزاكم الله خيرا على مجهوداتكم

**Comment by vzool** [comment]
وعليكم السلام ، يا أخي سوي
Pull Request (PR)
علشان مدير المخزن يوافق عليه
تحياتي

**Comment by vzool** [comment]
أنا رديت على صفحة مفتوحة من 10 ساعات ما حدثتها 
هههههههههههههههه
تحياتي لكم
