### ISSUE TITLE
Flutter Hijri Picker / Hijri package

### ISSUE THREAD

**Issue by ahmedoid** [SaudiOpenSourceCommunity/SaudiOSS#21]
I would like to thank you for this repository that has amazing projects.
https://pub.dartlang.org/packages/hijri
https://pub.dartlang.org/packages/hijri_picker#-example-tab-

**Comment by Alaboudi1** [comment]
يعطيك العافية مهندس أحمد. بإذن الله باضيفها في أقرب فرصة أذا ما سبقني لها أحد.
