### ISSUE TITLE
New open source packages

### ISSUE THREAD

**Issue by naifalshaye** [SaudiOpenSourceCommunity/SaudiOSS#26]
A Laravel Nova card to display world clocks
https://github.com/naifalshaye/worldclock

A Laravel Nova tool that integrates with Cpanel Mail to manage Email Addresses
https://github.com/naifalshaye/nova-cpanel-mail

A php laravel package to manage cPanel email accounts
https://github.com/naifalshaye/php-cpanel-email

A Laravel Nova field to play a SoundCloud audio
https://github.com/naifalshaye/soundcloud

A Nova field to place a marker on the map to get coordinates then it reverses geocoding the coordinates to get a street address
https://github.com/naifalshaye/nova-map-address

Nova address field that autocompletes the user input to show suggested addresses using Google Place service.
https://github.com/naifalshaye/nova-address-autocomplete

A Laravel Nova password field with generating random password option
https://github.com/naifalshaye/nova-random-password-generation

A Laravel Nova text field with a custom icon
https://github.com/naifalshaye/nova-text-field-with-icon

A Laravel Nova card to display PayPal current balance and latest transactions.
https://github.com/naifalshaye/nova-paypal

Saudi national ID number validation field for Laravel Nova, just for the frontend it will not prevent from submitting the form.
https://github.com/naifalshaye/nova-saudi-id-number-validation

Nova card that displays the latest user timeline and mentions tweets
https://github.com/naifalshaye/nova-twitter-timeline

A Laravel Nova toggle switch field
https://github.com/naifalshaye/toggle-switch

**Comment by Mohd-PH** [comment]
Thanks for contributing, added the new repos to the list
