### ISSUE TITLE
مكتبة دوت نت لتحويل ملفات html الى pdf

### ISSUE THREAD

**Issue by balbarak** [SaudiOpenSourceCommunity/SaudiOSS#27]
https://github.com/balbarak/WeasyPrint-netcore

**Comment by Alaboudi1** [comment]
ممكن بس تأكد لي أن أسمك هو بدر البراك؟

**Comment by balbarak** [comment]
صحيح

**Comment by Alaboudi1** [comment]
يعطيك العافية. أنا حاليا شغال على إضافة مشاريع أخرى بإذن الله بضيف مشروعك معهم.
