### ISSUE TITLE
Add new project to the list

### ISSUE THREAD

**Issue by lamoboos223** [SaudiOpenSourceCommunity/SaudiOSS#36]
المبرمج: لمى العصيمي
Python - web scraping [https://github.com/lamoboos223/web_scraping]
Python - facial landmarks [https://github.com/lamoboos223/facial-landmarks]
Vue js - whatsapp direct char [https://github.com/lamoboos223/whatsapp-direct-chat]

**Comment by Mohd-PH** [comment]
Thank you 👍
