### ISSUE TITLE
Saudi National Address API PHP Library with Laravel support

### ISSUE THREAD

**Issue by ali-alharthi** [SaudiOpenSourceCommunity/SaudiOSS#43]
SaudiAddress is a PHP package/library built to consume the Saudi National Address API (api.address.gov.sa). It makes it simple to use most of what the API has to offer.

You can for example retrieve regions, cities, districts, services and addresses from geo coordinates, verify an address and more!

[Repo](https://github.com/ali-alharthi/SaudiAddress)

Thanks in advance!

**Comment by Mohd-PH** [comment]
Great package!

Thank you for your efforts in expanding our Saudi Open Source Community !!! 🚀 🇸🇦
