### ISSUE TITLE
PhpSanitization and Uploady

### ISSUE THREAD

**Issue by fariscode511** [SaudiOpenSourceCommunity/SaudiOSS#46]
فكرة جميلة جداً اشكر القائمين عليها

و هاذي مشاريع بسيطة مني ان شاء الله تنضاف للقائمة

https://github.com/fariscode511/PhpSanitization

https://github.com/fariscode511/Uploady

المطور: فارس العتيبي

شكراً

**Comment by Mohd-PH** [comment]
يعطيك ألف عافية فارس @fariscode511 
بالعكس الشكر لك على هالمشاركة الجميلة لتطوير برمجيات مفتوحة المصدر سعودية 🇸🇦 🚀
