### ISSUE TITLE
NattyNote

### ISSUE THREAD

**Issue by ahmedelq** [SaudiOpenSourceCommunity/SaudiOSS#64]
هل أقدر أشارك بهذا المشروع؟ 
NattyNote: A browser extension to take time-stamped YouTube notes. 
[See more](https://github.com/ahmedelq/nattynote)

**Comment by Mohd-PH** [comment]
حياك الله اخ احمد
اكيد تقدر تشارك
اضفنا المشروع للقائمة
يعطيك العافية 🥇 🚀
