### ISSUE TITLE
Rendering issue for the homepage on mobile

### ISSUE THREAD

**Issue by Alaboudi1** [SaudiOpenSourceCommunity/SaudiOSS#83]
We were trying to update the dependencies for the homepage projects and encountered a few breaking changes that required updating the source code. While the homepage is rendering ok now, there are a few issues with viewing it from small devices (mobile).

It would be great if someone is willing to work on fixing these issues and improve the design slightly.

homepage link: https://saudiopensourcecommunity.github.io/SaudiOSS/

**Comment by mo9a7i** [comment]
are you open for a complete revamp of the homepage ? I'm working on something if you'd like me to continue

<https://mo9a7i.github.io/astro-saudi-oss-page/>

**Comment by Alaboudi1** [comment]
Yes, we need better UI for the homepage! Since you are doing this from scratch, maybe think about other possible interactions/features we can add for the homepage. cc @Mohd-PH

**Comment by Alaboudi1** [comment]
I do not want you to be overwhelm with major UI changes. We can always do incremental work with multiple PR.

**Comment by Mohd-PH** [comment]
I'm with anything that would make me ditch react 😀

**Comment by mo9a7i** [comment]
I've been used to building pages from scratch pretty quick using Astro and Tailwind lately, I'd be glad to attempt this.

Currently what I have in mind is something like this:
- use `dev.json` to get the developer names and info for the page
- enable dark/light mode  based on user machine preference. 
- it should be responsive on mobile
- not sure if I would be able to do Arabic/English versions without affecting SEO.
- Maybe a quick search and filter textarea to search for developers or repo names.
- **[If you got some ideas in mind, throw them in here and I'll do what I can.]**

I will see what else I can do, I'll do some research on similar projects. Will get back to you both soon. (tomorrow-ish or weekend max)

**Comment by mo9a7i** [comment]
Thanks and congrats on the new page [Astro SaudiOSS](https://saudiopensourcecommunity.github.io/SaudiOSS/)
