### ISSUE TITLE
اضافه مشروع URWAY 

### ISSUE THREAD

**Issue by ramisalem** [SaudiOpenSourceCommunity/SaudiOSS#86]
`
{
    "name": "ياسر طواش",
    "githubURL": "https://github.com/tawashy/urway.js",
    "projects": [
      {
        "name": "URWAY Payment Gateway",
        "URL": "https://github.com/tawashy/urway.js",
        "description": "The URWAY.js library provides convenient access to the URWAY API from applications written in server-side JavaScript.",
        "details": {}
      }
    ]
  }
`

**Comment by Mohd-PH** [comment]
Done 🚀
