### ISSUE TITLE
نقل إرشادات المشاركة ل CONTRIBUTEING.md

### ISSUE THREAD

**Issue by mo9a7i** [SaudiOpenSourceCommunity/SaudiOSS#92]
وش رايكم بتحويل إرشادات المشاركة إلى ملف `CONTRIBUTING.md` كما هو الحال في الممارسات الكويسة ؟

**Comment by Alaboudi1** [comment]
جميل، بس لازم تصير واضحه من الصفحة الرئيسية

**Comment by mo9a7i** [comment]
تم في #96
